{{- define "bytestash-container" -}}
name: {{ .Chart.Name }}-override
{{- if or .Values.volumeMounts .Values.persistence.enabled }}
volumeMounts:
{{- if .Values.persistence.enabled }}
- name: data
  mountPath: /data/snippets
  subPath: snippets
{{- end }}
{{- with .Values.volumeMounts }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
{{- end -}}
