{{- define "bytestash.deploy" }}
spec:
  template:
    spec:
      {{ include "corvid.podSpec" (list . "bytestash-podSpec") | indent 6 | trim }}
{{- end }}
{{- if .Values.deployment.enabled }}
{{- include "corvid.deploy" (list . "bytestash.deploy") }}
{{- end }}
