apiVersion: v2
appVersion: 1.4.0
description: A Helm chart for Kubernetes
name: piper
type: application
version: 0.2.0
dependencies:
- name: corvid
  version: 0.13.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
