apiVersion: v2
appVersion: 0.4.4
description: A Helm chart for Kubernetes
name: ollama
type: application
version: 0.2.1
dependencies:
- name: corvid
  version: 0.12.0
  repository: "https://gitlab.com/api/v4/projects/55284972/packages/helm/stable"
