apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: valkey
type: application
version: 0.1.0
dependencies:
- alias: valkey
  name: corvid-app
  version: 0.12.0
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
  condition: valkey.enabled
