# Default values for jellyfin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: lscr.io
  repository: linuxserver/jellyfin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "10.9.7"

persistence:
  enabled: true
  size: 8Gi
  accessModes:
  - ReadWriteOnce

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

command:
args:

## @param secrets [array] A list of secrets with a list of keys to turn into environment variables, these take precedence over everything else
secrets: []
#- name: jellyfin
#  lookup:
#  - key: jellyfinUsername
#    env: jellyfin_USERNAME
#  - key: jellyfinPassword
#    env: jellyfin_PASSWORD

## @param env [array] Raw helm environment variable settings for static or dynamic values
env:
- name: PUID
  value: "1001"
- name: PGID
  value: "1001"
- name: TZ
  value: "Etc/UTC"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  ## @param service.type [string] Service type
  type: ClusterIP

## @param ports [array] Ports to expose, tie to the service, and ingress
ports:
- name: http
  containerPort: 8096
  servicePort: 80
  protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: jellyfin.org.example
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: jellyfin.org.example-tls
  #    hosts:
  #      - jellyfin.org.example

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: data
  persistentVolumeClaim:
    claimName: jellyfin # change me to the name of pvc
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
# media dirs
- name: data
  mountPath: /data
  subPath: media
  readOnly: true
# config dir
- name: data
  mountPath: /config
  subPath: config
  readOnly: false

# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
