apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.ports }}
  - protocol: {{ .protocol }}
    port: {{ .servicePort }} # services in-cluster port
    targetPort: {{ .name }} # port of container/ pod
    name: {{ .name }}
  {{- end }}
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
