persistence:
  size: 8Gi
  accessModes:
  - ReadWriteOnce
  # dataSourceRef is only used to initialy migrate data
  # to the new generated pvc. Please ensure backup is enabled
  # to backup the initial data from this pvc.
  # Consider using migrationSnapshot to do the initial migration
  # instead.
  dataSourceRef: {}
    # #source initial data from snapshot
    # name: new-snapshot-test
    # kind: VolumeSnapshot
    # apiGroup: snapshot.storage.k8s.io
    # #source initial data from cloned pvc
    # kind: PersistentVolumeClaim
    # name: pvc-1

existingSecret: ""

backup:
  enabled: false
  schedule: "0 * * * 1"
  pruneIntervalDays: 1
  retain:
    hourly: 5
    daily: 4
    weekly: 3
    monthly: 2
    yearly: 1

restore:
  enabled: false
  schedule: "1 * * * 1"

migrationSnapshot:
  enabled: false
  pvc: ""
