persistence:
  generate: true
  size: 8Gi
  accessModes:
  - ReadWriteOnce

existingSecret: ""
# note this is only useful for backups not for restores
# please use dataSourceRef to pull from ReplicationDestination
# in the existing pvc itself
existingPVC: ""

backup:
  enabled: false
  schedule: "0 * * * 1"
  trigger: {}
  pruneIntervalDays: 1
  copyMethod: Snapshot # Snapshot or Clone or Direct see: https://volsync.readthedocs.io/en/stable/usage/restic/index.html#backup-options
  retain:
    hourly: 5
    daily: 4
    weekly: 3
    monthly: 2
    yearly: 1

restore:
  enabled: false
  schedule: "1 * * * 1"
  trigger: {}
