apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grocy.fullname" . }}
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grocy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grocy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grocy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          env:
          {{- .Values.env | toYaml | nindent 10 }}
          {{- range .Values.secrets }}
          {{- $secretContext := . }}
          {{- range .lookup }}
          - name: {{ .env }}
            valueFrom:
              secretKeyRef:
                name: {{ $secretContext.name }}
                key: {{ .key }}
                optional: false
          {{- end }}
          {{- end }}
          # TODO: find working endpoints
          #livenessProbe:
          #  httpGet:
          #    path: /api/version
          #    port: {{ (first .Values.ports).name }}
          #readinessProbe:
          #  httpGet:
          #    path: /api/version
          #    port: {{ (first .Values.ports).name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: data
            #mountPath: /var/www/data/
            mountPath: /config
            #subpath: data
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (print (include "grocy.fullname" . )) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
