{{- define "qbittorrent-container" -}}
{{- if or .Values.volumeMounts .Values.persistence.enabled }}
volumeMounts:
{{- if .Values.persistence.enabled }}
# media dirs
- name: data
  mountPath: /downloads
  subPath: downloads
  readOnly: false
# config dir
- name: data
  mountPath: /config
  subPath: config
  readOnly: false
{{- end }}
{{- with .Values.volumeMounts }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
{{- end -}}
