{{- define "qbittorrent.deploy" -}}
spec:
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "corvid.fullname" . }}
      containers:
      - {{ include "corvid.container" (list . "qbittorrent-container") | indent 8 | trim }}
{{- end -}}
{{- include "corvid.deploy" (list . "qbittorrent.deploy") -}}
