{{- define "qbittorrent.deploy" }}
spec:
  template:
    spec:
      {{ include "corvid.podSpec" (list . "qbittorrent-podSpec") | indent 6 | trim }}
{{- end }}
{{- include "corvid.deploy" (list . "qbittorrent.deploy") }}
