helm-chart-build:
  stage: build
  image:
    name: alpine/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
  - apk add --no-cache grep yq
  - git fetch --unshallow || echo "unshallow failed"
  - helm plugin install https://github.com/chartmuseum/helm-push.git
  - mkdir -p ./package
  - |
    for dir in ${CHARTS_DIR}/*/
    do
      DIR=${dir%*/} # removes trailing "/"
      #APP_VER=$(yq ".appVersion" ${DIR}/Chart.yaml | tr -d '"')
      APP_VER=$(yq ".image.tag" ${DIR}/values.yaml | tr -d '"')
      HELM_VER=$(yq ".version" ${DIR}/Chart.yaml | tr -d '"')
      #HELM_VER=$(git describe --abbrev=0 | tr -d '"' | tr -d 'v')
      echo "building ${DIR} chart (app: ${APP_VER}, chart: ${HELM_VER})"
      echo "helm dependency build ${DIR}"
      helm dependency build "${DIR}"/
      echo "helm package '${DIR}/' --destination ./package --app-version ${APP_VER} --version=${HELM_VER}"
      helm package "${DIR}/" --destination ./package --app-version ${APP_VER} --version=${HELM_VER}
    done
  artifacts:
    paths:
    - package/
