helm-chart-build:
  extends: [.helm]
  stage: build
  script:
  - git fetch --unshallow || echo "unshallow failed"
  - mkdir -p ./package
  - |
    for dir in ${CHARTS_DIR}/*/
    do
      DIR=${dir%*/} # removes trailing "/"
      APP_VER=$(yq ".image.tag" ${DIR}/values.yaml | tr -d '"')
      if [ "${APP_VER}" == "null" ]; then
        echo "appVersion falling back to ${DIR}/Chart.yaml"
        APP_VER=$(yq ".appVersion" ${DIR}/Chart.yaml | tr -d '"')
      fi
      HELM_VER=$(yq ".version" ${DIR}/Chart.yaml | tr -d '"')
      #HELM_VER=$(git describe --abbrev=0 | tr -d '"' | tr -d 'v')
      echo "building ${DIR} chart (app: ${APP_VER}, chart: ${HELM_VER})"
      echo "helm dependency build ${DIR}"
      helm dependency build "${DIR}"/
      echo "helm package '${DIR}/' --destination ./package --app-version ${APP_VER} --version=${HELM_VER}"
      helm package "${DIR}/" --destination ./package --app-version ${APP_VER} --version=${HELM_VER}
    done
  artifacts:
    paths:
    - package/
