# https://docs.gitlab.com/ee/user/packages/helm_repository/index.html#use-cicd-to-publish-a-helm-package
helm-chart-push:
  stage: deploy
  only:
  - main
  image:
    name: curlimages/curl:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
  - cd package
  # - export PACKAGE_FILE="$(ls)"
  - export HELM_PACKAGE_REGISTRY="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${CHANNEL}/charts"
  - |
    for file in *
    do
      echo "exporting ${file}"
      curl --request POST --fail-with-body --user gitlab-ci-token:${CI_JOB_TOKEN} --form "chart=@${file}" "${HELM_PACKAGE_REGISTRY}"
    done
  - echo "published to ${HELM_PACKAGE_REGISTRY}"
  needs:
  - job: helm-chart-build
    artifacts: true
