# https://docs.gitlab.com/ee/user/packages/helm_repository/index.html#use-cicd-to-publish-a-helm-package
helm-chart-push:
  extends: [.helm]
  stage: deploy
  only:
  - main
  script:
  # setting up helm repo to check for existing charts
  - export HELM_PACKAGE_REGISTRY="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${CHANNEL}/charts"
  - helm repo add --username ci --password ${CI_JOB_TOKEN} tmp ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  - helm repo update tmp
  - helm search repo tmp
  - cd package
  - regex='([a-zA-Z0-9_-]+)-([v0-9\.-]+)\.tgz'
  - ls -al
  - |
    for file in *
    do
      echo "file: '${file}'"
      CHART_NAME=$(echo ${file} | sed -E "s/$regex/\1/")
      CHART_VERSION=$(echo "${file}" | sed -E "s/$regex/\2/")
      if helm pull "tmp/${CHART_NAME}" --version ${CHART_VERSION}; then
        echo "verdict: ${CHART_NAME}:${CHART_VERSION} skipping"
      else
        echo "verdict: ${CHART_NAME}:${CHART_VERSION} publishing"
        curl --request POST --fail-with-body --user gitlab-ci-token:${CI_JOB_TOKEN} --form "chart=@${file}" "${HELM_PACKAGE_REGISTRY}"
      fi
    done
  - echo "published to ${HELM_PACKAGE_REGISTRY}"
  needs:
  - job: helm-chart-build
    artifacts: true
