generate-helm-readme:
  stage: build
  image:
    name: alpine/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
  - apk add --no-cache --update grep yq go
  - git fetch --unshallow || echo "unshallow failed"
  - go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.13.0
  - export PATH=$PATH:$(go env GOPATH)/bin
  - helm-docs
  - |
    for dir in ${CHARTS_DIR}/*/
    do
      DIR=${dir%*/} # removes trailing "/"
      #APP_VER=$(yq ".appVersion" ${DIR}/Chart.yaml | tr -d '"')
      APP_VER=$(yq ".image.tag" ${DIR}/values.yaml | tr -d '"')
      HELM_VER=$(yq ".version" ${DIR}/Chart.yaml | tr -d '"')
      #HELM_VER=$(git describe --abbrev=0 | tr -d '"' | tr -d 'v')
      echo "generating ${DIR} chart README.md parameters"
    done
