helm-chart-lint:
  extends: [.helm]
  stage: lint
  script:
    - |
      for dir in ${CHARTS_DIR}/*/
      do
        dir=${dir%*/} # removes trailing "/"
        echo "linting ${dir} chart"
        #helm dependency update "${dir}"
        helm dependency build "${dir}"
        helm lint "${dir}"/
        # on run if not 'corvid' chart
        if [ "${dir}" != "${CHARTS_DIR}/corvid" ]; then
          helm template "${dir}"/ | kubeconform -strict -kubernetes-version ${K8S_VERSION} \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{ .NormalizedKubernetesVersion }}/{{ .ResourceKind }}{{ .KindSuffix }}.json' \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
        fi
      done
