helm-chart-lint:
  stage: lint
  image:
    name: alpine/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - |
      apk add --no-cache git make musl-dev go
      export GOPATH=$HOME/.go
      export PATH=$PATH:$GOPATH/bin
      go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.7
      for dir in ${CHARTS_DIR}/*/
      do
        dir=${dir%*/} # removes trailing "/"
        echo "linting ${dir} chart"
        #helm dependency update "${dir}"
        helm dependency build "${dir}"
        helm lint "${dir}"/
        # on run if not 'corvid' chart
        if [ "${dir}" != "${CHARTS_DIR}/corvid" ]; then
          helm template "${dir}"/ | kubeconform -strict -kubernetes-version ${K8S_VERSION}
        fi
      done
