helm-chart-lint:
  stage: lint
  image:
    name: alpine/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - |
      for dir in ${CHARTS_DIR}/*/
      do
        dir=${dir%*/} # removes trailing "/"
        echo "linting ${dir} chart"
        helm dependency build "${dir}"
        helm lint "${dir}"/
        helm template "${dir}"/ | kubeconform -strict -kubernetes-version ${K8S_VERSION}
      done
