{{- define "rook-wipe.podSpec" -}}
nodeName: {{ .Values.nodeName }} # schedule pod to specific node
containers:
- {{ include "corvid.container" (list . "rook-wipe.container") | indent 2 | trim }}
{{- end -}}
