apiVersion: v2
name: cyberchef
description: The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis
type: application
version: 0.1.0
appVersion: "v10.19.4"
dependencies:
  - alias: cyberchef
    name: corvid-app
    version: 0.10.3
    repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
    condition: cyberchef.enabled
