{{- define "ollama-container" -}}
{{- if or .Values.volumeMounts .Values.persistence.enabled }}
volumeMounts:
{{- if .Values.persistence.enabled }}
- name: data
  mountPath: /root/.ollama/
  subpath: data
{{- end }}
{{- with .Values.volumeMounts }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
{{- end -}}
