stages:
  - lint
  - build
  - test
  - deploy

variables:
  CHANNEL: "stable"
  CHARTS_DIR: "charts"

  BUILDX_VERSION: "v0.12.1" # https://github.com/docker/buildx/releases
  BUILDX_ARCH: "linux-amd64" # I.E what architecture we are building FROM
  BUILDX_TARGET_ARCHES: "linux/amd64,linux/arm64/v8" # what architecture we are building FOR
  DOCKERFILE_PATH: "operator/Dockerfile" # relative path to dockerfile from project root directory
  DOCKERFILE_DIR: "operator" # relative path to dockerfile from project root directory
  CONTAINER_NAME: "copy-container"
  PAGES_DIR: "public"

# REUSABLE CONDITIONAL RULES FOR PIPELINE TRIGGERS
.rules_default_branch_push:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"

.rules_default_branch_tag:
  rules:
    - if: $CI_COMMIT_TAG

.rules_nondefault_branch_push:
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == "" && $CI_PIPELINE_SOURCE == "push"

include:
- local: /.gitlab/helm/lint.yaml
- local: /.gitlab/helm/build.yaml
- local: /.gitlab/helm/push.yaml
