stages:
  - .pre
  - lint
  - build
  - test
  - deploy

variables:
  #PRE_COMMIT_DEDUPLICATE_MR_AND_BRANCH: false
  #PRE_COMMIT_AUTO_FIX_BRANCH_ONLY: true

  CHANNEL: "stable"
  CHARTS_DIR: "charts"
  K8S_VERSION: "1.30.3" # renovate: datasource=github-tags depName=kubernetes/kubernetes

  BUILDX_VERSION: "v0.12.1" # https://github.com/docker/buildx/releases
  BUILDX_ARCH: "linux-amd64" # I.E what architecture we are building FROM
  BUILDX_TARGET_ARCHES: "linux/amd64,linux/arm64/v8" # what architecture we are building FOR
  DOCKERFILE_PATH: "operator/Dockerfile" # relative path to dockerfile from project root directory
  DOCKERFILE_DIR: "operator" # relative path to dockerfile from project root directory
  CONTAINER_NAME: "copy-container"
  PAGES_DIR: "public"

# REUSABLE CONDITIONAL RULES FOR PIPELINE TRIGGERS
.rules_default_branch_push:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"

.rules_default_branch_tag:
  rules:
    - if: $CI_COMMIT_TAG

.rules_nondefault_branch_push:
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == "" && $CI_PIPELINE_SOURCE == "push"

.helm:
  image:
    name: alpine:3.21.3
    entrypoint: ["/bin/sh", "-c"]
  cache:
    paths:
    - "${CI_PROJECT_DIR}/.gocache"
  before_script:
  - |
    apk add --no-cache \
    grep=~3.11 \
    go=~1.23 \
    helm=~3.16
  # creating cache dir that HAS to be inside project workspace
  - mkdir -p ${CI_PROJECT_DIR}/.gocache
  - export GOPATH=${CI_PROJECT_DIR}/.gocache
  - export PATH=$PATH:$GOPATH/bin
  - go install github.com/mikefarah/yq/v4@v4.45.1
  - go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.7
  - go install github.com/go-task/task/v3/cmd/task@v3.42.1

include:
- local: /.gitlab/helm/lint.yaml
- local: /.gitlab/helm/build.yaml
# - local: /.gitlab/helm/generate.yaml
- local: /.gitlab/helm/deploy-helm.yaml
- local: /.gitlab/helm/deploy-oci.yaml
