apiVersion: v2
appVersion: "4.6.5-r0-ls336"
description: A Helm chart for Kubernetes
name: qbittorrent
type: application
version: 0.1.0
dependencies:
- name: corvid
  version: 0.5.2
  repository: "file://../corvid"
