{{- if .Values.barcode.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "barcode.fullname" . }}
spec:
  accessModes:
  {{- range .Values.barcode.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.barcode.persistence.size | quote }}
{{- end }}
