{{- if .Values.barcode.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "barcode.serviceAccountName" . }}
  labels:
    {{- include "barcode.labels" . | nindent 4 }}
  {{- with .Values.barcode.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
