{{- define "corvid-app.deploy" }}
spec:
  template:
    spec:
      {{ include "corvid.podSpec" (list . "corvid-app-podSpec") | indent 6 | trim }}
{{- end }}
{{- if .Values.deployment.enabled }}
{{- include "corvid.deploy" (list . "corvid-app.deploy") }}
{{- end }}
