apiVersion: v2
appVersion: "39-full"
description: A Helm chart for Kubernetes
name: renovate
type: application
version: 0.6.0
dependencies:
- alias: renovate
  name: corvid-app
  version: 0.17.0
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
