{{- define "corvid.container.tpl" -}}
name: {{ .Chart.Name }}
# Security Context
{{- if .Values.securityContextEnabled }}
# Default Security Context
{{- if not .Values.securityContext }}
{{- with .Values.securityContextDefault }}
securityContext:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
# Overriden Security Context
{{- if .Values.securityContext }}
{{- with .Values.securityContext }}
securityContext:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.command }}
command:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.args }}
args:
  {{- toYaml . | nindent 2 }}
{{- end }}
ports:
  {{- range .Values.ports }}
  - name: {{ .name }}
    containerPort: {{ .containerPort }}
    protocol: {{ .protocol }}
  {{- end }}
{{- with .Values.envFrom }}
envFrom:
  {{- toYaml . | nindent 2 }}
{{- end }}
env:
{{- .Values.env | toYaml | nindent 2 }}
{{- with .Values.secrets }}
{{- range . }}
{{- $secretContext := . }}
{{- range .lookup }}
  - name: {{ .env }}
    valueFrom:
      secretKeyRef:
        name: {{ $secretContext.name }}
        key: {{ .key }}
        optional: false
{{- end }}
{{- end }}
{{- end }}
# Startup Probe
{{- if .Values.startupProbeEnabled }}
{{- with .Values.startupProbe }}
# overriden startupProbe
startupProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if not .Values.startupProbe }}
{{- with .Values.startupProbeDefault }}
# default startupProbe
startupProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
# Liveness Probe
{{- if .Values.livenessProbeEnabled }}
{{- with .Values.livenessProbe }}
# overriden livenessProbe
livenessProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if not .Values.livenessProbe }}
{{- with .Values.livenessProbeDefault }}
# default livenessProbe
livenessProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
# Readiness Probe
{{- if .Values.readinessProbeEnabled }}
{{- with .Values.readinessProbe }}
# overriden readinessProbe
readinessProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if not .Values.readinessProbe }}
{{- with .Values.readinessProbeDefault }}
# default readinessProbe
readinessProbe:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
# Resources
{{- if .Values.resourcesEnabled }}
{{- with .Values.resources }}
# overriden resources
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if not .Values.resources }}
{{- with .Values.resourcesDefault }}
# default resources
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- if or (.Values.volumeMounts) (and (.Values.persistence.enabled) (.Values.persistence.defaultVolumeMounts)) }}
# volumeMounts both default and overrides
volumeMounts:
{{- if .Values.persistence.enabled }}
{{- with .Values.persistence.defaultVolumeMounts }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- with .Values.volumeMounts }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end -}}
{{- define "corvid.container" -}}
{{- include "corvid.util.merge" (append . "corvid.container.tpl") -}}
{{- end -}}
