{{- define "corvid.job.tpl" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "corvid.fullname" . }}
  labels:
    {{- include "corvid.labels" . | nindent 4 }}
  {{- with .Values.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "corvid.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "corvid.podSpec.tpl" . | indent 6 }}
      restartPolicy: Never
{{- end -}}
{{- define "corvid.job" -}}
{{- include "corvid.util.merge" (append . "corvid.job.tpl") -}}
{{- end -}}
