{{- define "corvid.netpol.tpl" -}}
{{- if .Values.netpol.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "corvid.fullname" . }}
  labels:
    {{- include "corvid.labels" . | nindent 4 }}
spec:
  podSelector:
    {{- include "corvid.selectorLabels" . | nindent 4 }}
  policyTypes:
  - Egress
  egress:
  - to:
    # allow to go to WAN internet
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  - to:
    # allow DNS lookups
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    # on specific ports
    ports:
    - protocol: UDP
      port: 53
  - to:
    # allow egress to other pods in this namespace
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- end }}
{{- end -}}
{{- define "corvid.netpol" -}}
{{- include "corvid.util.merge" (append . "corvid.netpol.tpl") -}}
{{- end -}}
