{{- define "corvid.podSpec.tpl" -}}
{{- with .Values.runtimeClassName }}
runtimeClassName: {{ . }}
{{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
serviceAccountName: {{ include "corvid.serviceAccountName" . }}
securityContext:
  {{- toYaml .Values.podSecurityContext | nindent 2 }}
{{- with .Values.initContainers }}
initContainers:
  {{- toYaml . | nindent 2 }}
{{- end }}
containers:
- {{ include "corvid.container.tpl" . | indent 2 | trim }}
# if volumes set or persistence enabled
{{- if or .Values.volumes .Values.persistence.enabled }}
volumes:
  {{- if .Values.persistence.enabled }}
  - name: data
    persistentVolumeClaim:
      claimName: {{ include "corvid.fullname" . }}
  {{- end }}
  {{- with .Values.volumes }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- with .Values.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.affinity }}
affinity:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.tolerations }}
tolerations:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- define "corvid.podSpec" -}}
{{- include "corvid.util.merge" (append . "corvid.podSpec.tpl") -}}
{{- end -}}
