{{- define "corvid.podSpec.tpl" -}}
{{- with .Values.runtimeClassName }}
runtimeClassName: {{ . }}
{{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
serviceAccountName: {{ include "corvid.serviceAccountName" . }}
# Pod Security Context
{{- if .Values.podSecurityContextEnabled }}
# Default Pod Security Context
{{- if not .Values.podSecurityContext }}
{{- with .Values.podSecurityContextDefault }}
securityContext:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
# Overriden Pod Security Context
{{- if .Values.podSecurityContext }}
{{- with .Values.podSecurityContext }}
securityContext:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- with .Values.initContainers }}
initContainers:
  {{- toYaml . | nindent 2 }}
{{- end }}
containers:
- {{ include "corvid.container.tpl" . | indent 2 | trim }}
# if volumes set or persistence enabled
{{- if or .Values.volumes (or .Values.persistence.enabled .Values.persistence.existingClaim) }}
volumes:
  {{- if .Values.persistence.existingClaim }}
  - name: data
    persistentVolumeClaim:
      claimName: {{ .Values.persistence.existingClaim }}
  {{- else if .Values.persistence.enabled }}
  - name: data
    persistentVolumeClaim:
      claimName: {{ include "corvid.fullname" . }}
  {{- end }}
  {{- with .Values.volumes }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- with .Values.dnsPolicy }}
dnsPolicy: {{ . }}
{{- end }}
{{- with .Values.dnsConfig }}
dnsConfig:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.affinity }}
affinity:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.tolerations }}
tolerations:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- define "corvid.podSpec" -}}
{{- include "corvid.util.merge" (append . "corvid.podSpec.tpl") -}}
{{- end -}}
