{{- define "corvid.pvc.tpl" -}}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "corvid.fullname" . }}
  labels:
    {{- include "corvid.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end -}}
{{- define "corvid.pvc" -}}
{{- include "corvid.util.merge" (append . "corvid.pvc.tpl") -}}
{{- end -}}
