{{- define "corvid.sa.tpl" -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corvid.serviceAccountName" . }}
  labels:
    {{- include "corvid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end -}}
{{- define "corvid.sa" -}}
{{- include "corvid.util.merge" (append . "corvid.sa.tpl") -}}
{{- end -}}
