{{- define "corvid.svc.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "corvid.fullname" . }}
  labels:
    {{- include "corvid.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.ports }}
  - protocol: {{ .protocol }}
    port: {{ .servicePort }} # services in-cluster port
    targetPort: {{ .name }} # port of container/ pod
    name: {{ .name }}
    {{- with .appProtocol }}
    appProtocol: {{ . }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "corvid.selectorLabels" . | nindent 4 }}
{{- end -}}
{{- define "corvid.svc" -}}
{{- include "corvid.util.merge" (append . "corvid.svc.tpl") -}}
{{- end -}}
