{{- define "pgadmin.deploy" }}
spec:
  template:
    spec:
      {{ include "corvid.podSpec" (list . "pgadmin-podSpec") | indent 6 | trim }}
{{- end }}
{{- include "corvid.deploy" (list . "pgadmin.deploy") }}
