{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- include "corvid.pvc" (list . "faster-whisper.pvc") -}}
{{- end }}
{{- define "faster-whisper.pvc" -}}
{{- end -}}
