apiVersion: v2
appVersion: "2026.3.0" # renovate: datasource=docker depName=docker.io/cloudflare/cloudflared
description: A Helm chart for Kubernetes
name: cloudflared
type: application
version: 0.6.1
dependencies:
- name: corvid
  version: 0.13.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
