# Default values for rook-wipe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeName: exampleHostName

## @param replicaCount [string] Server deployment replica count
replicaCount: 1

image:
  ## @param image.registry [string] Image container registry
  registry: docker.io
  ## @param image.repository [string] Image repository
  repository: library/busybox
  ## @param image.pullPolicy [string] Image pull policy
  pullPolicy: IfNotPresent
  ## @param image.tag [string] Overrides the image tag whose default is the chart appVersion.
  tag: ""

persistence:
  enabled: false
  size: 8Gi
  accessModes:
  - ReadWriteOnce
  existingClaim: ""

command:
- "/bin/sh"
- "-c"
- |
  set -e
  if [[ -z "$DEVICES" ]]; then
    echo "No devices specified"
    exit 1
  else
    rm -rf /node/rook-data/*
    IFS=','
    for device in $DEVICES; do
      dd if=/dev/zero of=${device} bs=1M count=100 oflag=direct
    unset IFS
    done
  fi

args:
runtimeClassName:

cron:
  # -- enable or disable cronjob
  enabled: true
  # -- schedule for cronjob using Cron syntax https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#schedule-syntax
  schedule: "@midnight"
  # -- cronjob will not trigger on schedule but can be manually triggered
  suspend: true

## @param initContainers Add bespoke init containers to the pods
initContainers: []
# - name: some-pod-name
#   image: some-image
#   imagePullPolicy: Always
#   ports:
#     - name: some-port
#       containerPort: 1234

restartPolicy: Always

## @param imagePullSecrets [array] Image pull secrets
imagePullSecrets: []
## @param nameOverride [string] Partial name override
nameOverride: ""
## @param fullnameOverride [string] Full name override
fullnameOverride: ""

## @param secrets [array] A list of secrets with a list of keys to turn into environment variables, these take precedence over everything else
secrets: []
# - name: rook-wipe
#   lookup:
#   - key: rook-wipeUsername
#     env: rook-wipe_USERNAME
#   - key: rook-wipePassword
#     env: rook-wipe_PASSWORD

## @param env [array] Raw helm environment variable settings for static or dynamic values
env:
- name: DEVICES
  value: ""

## @param envFrom [array] Raw container envFrom https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#container-v1-core
envFrom:
# - configMapRef:
#     name: someConfigMap
#     optional: false
# - secretRef:
#     name: someSecret
#     optional: false

serviceAccount:
  ## @param serviceAccount.create [string] Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  ## @param serviceAccount.annotations [object] Annotations to add to the service account
  annotations: {}
  ## @param serviceAccount.name [string] The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

## @param podAnnotations [object] Pod annotations
podAnnotations: {}
podLabels: {}

# -- enable or disable podSecurityContext entirely
podSecurityContextEnabled: true
# -- default podSecurityContext if none specified
podSecurityContextDefault: {}
  # fsGroup: 1000
# -- podSecurityContext for consumer overrides
podSecurityContext: {}
  # fsGroup: 1000

# -- enable or disable securityContext entirely
securityContextEnabled: true
# -- default securityContext if none specified
securityContextDefault:
  privileged: true # must be privileged to clean disks etc
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 1000
  # allowPrivilegeEscalation: false
# -- securityContext for consumer overrides
securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  ## @param service.type [string] Service type
  type: ClusterIP

## @param ports [array] Ports to expose, tie to the service, and ingress
ports:
- name: http
  containerPort: 8080
  servicePort: 80
  protocol: TCP

ingress:
  ## @param ingress.enabled [string] Enable ingress
  enabled: false
  ## @param ingress.className [string] Ingress class
  className: ""
  ## @param ingress.annotations [object] Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  ## @param ingress.hosts [array] Ingress hosts
  hosts:
    - host: rook-wipe.org.example
      paths:
        - path: /
          pathType: ImplementationSpecific
  ## @param ingress.tls [array] Ingress TLS
  tls: []
  #  - secretName: rook-wipe.org.example-tls
  #    hosts:
  #      - rook-wipe.org.example

# -- enable or disable resources entirely
resourcesEnabled: true
# -- default resources if not specified by user
resourcesDefault:
  limits:
    memory: 200Mi
  requests:
    cpu: 1000m
# -- raw resources block overrides for user
resources:
  # limits:
  #   memory: 128Mi
  # requests:
  #   cpu: 100m

# -- enable or disable startup probe entirely
startupProbeEnabled: false
# -- default startup probe if not specified by user
startupProbeDefault:
  httpGet:
    path: /
    port: http
# -- raw startup probe overrides for user
startupProbe:
  # httpGet:
  #   path: /
  #   port: http

# -- enable or disable liveness probe entirely
livenessProbeEnabled: false
# -- default liveness probe if not specified by user
livenessProbeDefault:
  httpGet:
    path: /
    port: http
# -- raw liveness probe overrides for user
livenessProbe:
  # httpGet:
  #   path: /
  #   port: http

# -- enable or disable readiness probe entirely
readinessProbeEnabled: false
# -- default readiness probe if not specified by user
readinessProbeDefault:
  httpGet:
    path: /
    port: http
# -- raw readiness probe overrides for user
readinessProbe:
  # httpGet:
  #   path: /
  #   port: http

autoscaling:
  ## @param autoscaling.enabled [string] Enable autoscaling
  enabled: false
  ## @param autoscaling.minReplicas [string] Minimum number of replicas
  minReplicas: 1
  ## @param autoscaling.maxReplicas [string] Maximum number of replicas
  maxReplicas: 100
  ## @param autoscaling.targetCPUUtilizationPercentage [string] Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: rook-data-dir
  hostPath:
    # usually /var/lib/rook
    path: /var/lib/rook
- name: dev
  hostPath:
    path: /dev
    type: Directory

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: rook-data-dir
  mountPath: /node/rook-data
- name: dev
  mountPath: /dev

nodeSelector: {}

tolerations: []

affinity: {}

netpol:
  enabled: true

dnsPolicy: "" # default is ClusterFirst
dnsConfig: {}
  # nameservers:
  # - 1.1.1.1
  # options:
  # - name: ndots
  #   value: "1"
