{{- define "open-webui-container" -}}
{{- if or .Values.volumeMounts .Values.persistence.enabled }}
volumeMounts:
{{- if .Values.persistence.enabled }}
- name: data
  mountPath: /app/backend/data/
  subPath: data
{{- end }}
{{- with .Values.volumeMounts }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
{{- end -}}
