{{- if not .Values.configMap.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ha.fullname" . }}
  labels:
    {{- include "ha.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- .Values.configMap.configuration | nindent 4 }}
{{- end }}
