apiVersion: v2
appVersion: "2026.8.3" # renovate: datasource=docker depName=ghcr.io/home-assistant/home-assistant
description: A Helm chart for Kubernetes
name: home-assistant
type: application
version: 0.17.1
dependencies:
- name: corvid
  version: 0.13.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
