apiVersion: v2
appVersion: "2024.12.5"
description: A Helm chart for Kubernetes
name: home-assistant
type: application
version: 0.7.0
dependencies:
- name: corvid
  version: 0.12.0
  repository: "file://../corvid"
