{{- if .Values.backup.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ include "backupd.fullname" . }}-backup
  labels:
    {{- include "backupd.labels" . | nindent 4 }}
spec:
  # The PVC to be backed up
  sourcePVC: {{ .Values.existingPVC | default (include "backupd.fullname" .) }}
  {{- if .Values.backup.trigger }}
  trigger:
    {{- toYaml .Values.backup.trigger | nindent 4 }}
  {{- else }}
  trigger:
    schedule: {{ .Values.backup.schedule }}
  {{- end }}
  restic:
    # Prune the repository (repack to free space) every week
    pruneIntervalDays: {{ .Values.backup.pruneIntervalDays }}
    # Name of the Secret with the connection information
    repository: {{ .Values.existingSecret | default (include "backupd.fullname" .) }}
    # Retention policy for backupds
    retain: {{- toYaml .Values.backup.retain | nindent 6 }}
    # Clone the source volume prior to taking a backupd to ensure a
    # point-in-time image.
    copyMethod: {{ .Values.backup.copyMethod }}
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    #storageClassName: my-sc-name
    # The VSC to use if the copy method is Snapshot (default if omitted)
    #volumeSnapshotClassName: my-vsc-name
{{- end }}
