apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ include "backupd.fullname" . }}
  labels:
    {{- include "backupd.labels" . | nindent 4 }}
spec:
  # The PVC to be backed up
  sourcePVC: {{ include "backupd.fullname" . }}
  trigger:
    schedule: {{ .Values.backup.schedule }}
  restic:
    # Prune the repository (repack to free space) every week
    pruneIntervalDays: {{ .Values.backup.pruneIntervalDays }}
    # Name of the Secret with the connection information
    repository: {{ include "backupd.fullname" . }}
    # Retention policy for backupds
    retain:
      hourly: 5
      daily: 4
      weekly: 3
      monthly: 2
      yearly: 1
    # Clone the source volume prior to taking a backupd to ensure a
    # point-in-time image.
    copyMethod: Snapshot #Clone
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    #storageClassName: my-sc-name
    # The VSC to use if the copy method is Snapshot (default if omitted)
    #volumeSnapshotClassName: my-vsc-name
