kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "backupd.fullname" . }}
  labels:
    {{- include "backupd.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: {{ include "backupd.fullname" . }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
