{{- if .Values.restore.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: {{ include "backupd.fullname" . }}-restore
  labels:
    {{- include "backupd.labels" . | nindent 4 }}
spec:
  trigger:
    schedule: {{ .Values.restore.schedule }}
  restic:
    repository: {{ .Values.existingSecret | default (include "backupd.fullname" .) }}
    copyMethod: Snapshot
    accessModes:
    {{- range .Values.persistence.accessModes }}
      - {{ . | quote }}
    {{- end }}
    capacity: {{ .Values.persistence.size | quote }}
{{- end }}
