apiVersion: v2
appVersion: 1.5.11 # renovate: datasource=docker depName=ghcr.io/jordan-dalby/bytestash
description: A Helm chart for Kubernetes
name: bytestash
type: application
version: 0.1.5
dependencies:
- name: corvid
  version: 0.13.1
  repository: "oci://registry.gitlab.com/georgeraven/raven-helm-charts"
