name: Deploy Helm Charts to OCI Registry
on:
  workflow_call:

env:
  CHARTS_DIR: "charts"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    container:
      image: alpine/helm:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Set Environment Variables and Paths the GitHub Way
      run: |
        export GOPATH=$HOME/.go
        echo "GOPATH=$HOME/.go" >> $GITHUB_ENV
        echo "$GOPATH/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: |
        apk add --no-cache git tree make musl-dev go

    - name: Download Artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
      with:
        name: charts
        path: package

    - name: Debug Artifacts
      run: |
        tree .

    - name: Login to GHCR OCI Registry
      run: |
        helm registry login ghcr.io -u DreamingRaven -p ${{ secrets.GITHUB_TOKEN }}
      env:
        HELM_EXPERIMENTAL_OCI: '1'

    - name: Helm Push Artifacts if Version Doesn't Exist
      run: |
        cd package
        for filename in *.tgz; do
          echo "*************************************"
          regex='([a-zA-Z0-9_-]+)-([v0-9\.-]+)\.tgz'
          chart_name=$(echo "$filename" | sed -E "s/$regex/\1/")
          chart_version=$(echo "$filename" | sed -E "s/$regex/\2/")
          echo "${chart_name} ${chart_version}"
          echo "Pulling ${chart_name} ${chart_version} to ghcr.io/dreamingraven"
          if helm pull oci://ghcr.io/dreamingraven/"${chart_name}" --version "${chart_version}"; then
            echo "${chart_name} ${chart_version} exists, skipping ..."
          else
            echo "Pushing ${chart_name} ${chart_version} to ghcr.io/dreamingraven"
            helm push "${filename}" oci://ghcr.io/dreamingraven/
          fi
          echo "*************************************"
        done
      env:
        HELM_EXPERIMENTAL_OCI: '1'
      shell: bash

